In [1]:
import sys
sys.path.append("../") 

In [2]:
import numpy as np
from nn.layers.dense import Dense

In [3]:
X = np.array([
    np.array([5, 2])
]).T

X

array([[5],
       [2]])

In [4]:
y = np.array([
    np.array([1]), 
    np.array([2]),
    np.array([3])
])

y

array([[1],
       [2],
       [3]])

In [5]:
layer = Dense(X.shape[0], 3, activation="sigmoid", has_bias=True, initialization="random")

In [6]:
old_weights = layer.weights.copy()
old_weights

array([[-0.42829353, -0.12481491],
       [ 0.03425781, -0.65613467],
       [-0.61768308,  1.22811308]])

In [7]:
old_bias = layer.bias.copy()
old_bias

array([[0.60405384],
       [0.9187542 ],
       [0.18729171]])

In [8]:
layer.activation

<function nn.activations.sigmoid(x: float) -> float>

In [9]:
layer.activation_derivative

<function nn.activations.sigmoid_derivative(x: float) -> float>

In [10]:
layer.forward(X)

array([[0.14343556],
       [0.44467099],
       [0.3905746 ]])

In [11]:
loss = 1/2 * (y - layer.a)**2
loss

array([[0.36685132],
       [1.20952416],
       [3.40455045]])

In [12]:
loss_derivative = (y - layer.a)
loss_derivative

array([[0.85656444],
       [1.55532901],
       [2.6094254 ]])

In [13]:
layer.backward(loss_derivative)

array([[-0.41556572],
       [ 0.49765727]])

In [14]:
layer.delta

array([[0.10523905],
       [0.38407092],
       [0.6211113 ]])

In [15]:
layer.d_weights

array([[0.52619525, 0.2104781 ],
       [1.92035462, 0.76814185],
       [3.10555652, 1.24222261]])

In [16]:
layer.d_bias

array([[0.10523905],
       [0.38407092],
       [0.6211113 ]])

In [17]:
layer.update_parameters()

In [18]:
layer.weights, old_weights

(array([[-0.43355549, -0.12691969],
        [ 0.01505427, -0.66381609],
        [-0.64873865,  1.21569085]]),
 array([[-0.42829353, -0.12481491],
        [ 0.03425781, -0.65613467],
        [-0.61768308,  1.22811308]]))

In [19]:
layer.bias, old_bias

(array([[0.60300145],
        [0.91491349],
        [0.1810806 ]]),
 array([[0.60405384],
        [0.9187542 ],
        [0.18729171]]))

In [20]:
layer2 = Dense(X.shape[0], 3, activation="sigmoid", has_bias=False, initialization="random")

In [21]:
old_weights = layer2.weights.copy()
old_weights

array([[ 1.79837705,  1.42187715],
       [ 0.79360812, -0.30735831],
       [ 0.42714322, -0.34276844]])

In [22]:
old_bias = layer2.bias.copy()
old_bias

array([[0.],
       [0.],
       [0.]])

In [23]:
layer2.forward(X)

array([[0.99999276],
       [0.96621352],
       [0.81002601]])

In [24]:
loss = 1/2 * (y - layer2.a)**2
loss

array([[2.62215181e-11],
       [5.34357248e-01],
       [2.39799304e+00]])

In [25]:
loss_derivative = (y - layer2.a)
loss_derivative

array([[7.24175643e-06],
       [1.03378648e+00],
       [2.18997399e+00]])

In [26]:
layer2.backward(loss_derivative)

array([[ 0.1707306 ],
       [-0.12588624]])

In [27]:
layer2.delta

array([[5.24426564e-11],
       [3.37479164e-02],
       [3.37001677e-01]])

In [28]:
layer2.d_weights

array([[2.62213282e-10, 1.04885313e-10],
       [1.68739582e-01, 6.74958328e-02],
       [1.68500839e+00, 6.74003355e-01]])

In [29]:
layer2.d_bias

In [30]:
layer2.update_parameters()

In [31]:
layer2.weights, old_weights

(array([[ 1.79837705,  1.42187715],
        [ 0.79192072, -0.30803327],
        [ 0.41029313, -0.34950848]]),
 array([[ 1.79837705,  1.42187715],
        [ 0.79360812, -0.30735831],
        [ 0.42714322, -0.34276844]]))

In [32]:
layer2.bias, old_bias

(array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]]))