In [30]:
import sys
sys.path.append("../") 

In [31]:
import numpy as np
from nn.layers.dense import Dense
from nn.models.sequential import Sequential

In [32]:
model = Sequential()
model.add(Dense(2, 3, activation="sigmoid", has_bias=True, initialization="random"))
model.add(Dense(3, 1, activation="sigmoid", has_bias=True, initialization="random"))
model.compile(epochs=10000, learning_rate=1, optimizer="sgd", batch_size=2, loss="mse")

In [33]:
X = np.array([
    np.array([0.5, 0.2]),
    np.array([0.1, 0.6])
])

X

array([[0.5, 0.2],
       [0.1, 0.6]])

In [34]:
y = np.array([
    np.array([0.7, 0.8])
])

y

array([[0.7, 0.8]])

In [35]:
model.fit(X, y)

Epoch 0 Loss: 0.03778686282404953
Epoch 1 Loss: 0.018347891755371708
Epoch 2 Loss: 0.00963363626730387
Epoch 3 Loss: 0.005667289171273385
Epoch 4 Loss: 0.0037205005041899327
Epoch 5 Loss: 0.0026940887307245697
Epoch 6 Loss: 0.0021214023522436415
Epoch 7 Loss: 0.0017876593994809412
Epoch 8 Loss: 0.0015864755955090869
Epoch 9 Loss: 0.0014618770959847047
Epoch 10 Loss: 0.0013829502930585642
Epoch 11 Loss: 0.0013319471936223547
Epoch 12 Loss: 0.001298356989084021
Epoch 13 Loss: 0.0012757975060022724
Epoch 14 Loss: 0.0012603145704263934
Epoch 15 Loss: 0.0012494179838861213
Epoch 16 Loss: 0.0012415185696991481
Epoch 17 Loss: 0.0012355911473857979
Epoch 18 Loss: 0.0012309685194170012
Epoch 19 Loss: 0.001227213330301979
Epoch 20 Loss: 0.0012240371952827193
Epoch 21 Loss: 0.0012212490388674884
Epoch 22 Loss: 0.0012187217580503832
Epoch 23 Loss: 0.0012163705289931171
Epoch 24 Loss: 0.00121413859177389
Epoch 25 Loss: 0.001211987881421006
Epoch 26 Loss: 0.0012098928234310757
Epoch 27 Loss: 0.00120

In [36]:
model.predict(X)

array([[0.7, 0.8]])